# configurations on my terminal so that my home directory is clean and organized
# it is based on the XDG Base Directory Specification
# particularly thanks to these 3 sources:
#
# https://wiki.archlinux.org/title/XDG_Base_Directory
# https://odysee.com/@Luke:7/spring-cleaning-your-home-that-is:7
# https://github.com/b3nj5m1n/xdg-ninja?tab=readme-ov-file#xdg-ninja

# Hledger file
export LEDGER_FILE="${XDG_DOCUMENTS_DIR:-$HOME/Documents}/Areas/Finances/main.journal"
export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
export AZURE_CONFIG_DIR="$XDG_DATA_HOME/azure"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export GOPATH="$XDG_DATA_HOME/go"
export PATH="$GOPATH/bin:$PATH"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export XCURSOR_PATH="/usr/share/icons:$XDG_DATA_HOME/icons"
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export OMNISHARPHOME="$XDG_DATA_HOME/omnisharp"
export PARALLEL_HOME="$XDG_DATA_HOME/parallel"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"
export PLATFORMIO_CORE_DIR="$XDG_DATA_HOME/platformio"
export PSQL_HISTORY="$XDG_DATA_HOME/psql_history"
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export VJA_CONFIGDIR="$XDG_CONFIG_HOME/vja"

export STACK_XDG=1
export STACK_ROOT="$XDG_DATA_HOME/stack"

export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"
export ZDOTDIR="$HOME"/.config/zsh
export WORKON_HOME="$XDG_DATA_HOME/virtualenvs"
export W3M_DIR="$XDG_DATA_HOME/w3m"

export DOTNET_CLI_HOME="$XDG_DATA_HOME"/dotnet
export PATH="$PATH:$DOTNET_CLI_HOME/tools:$DOTNET_CLI_HOME/.dotnet/tools"
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export OMNISHARPHOME="$XDG_CONFIG_HOME"/omnisharp
export DOTNET_ROLL_FORWARD=LatestMajor

# for _history files generated by rlwrap
export RLWRAP_HOME="$XDG_DATA_HOME/rlwrap"

export NUGET_PACKAGES="$XDG_CACHE_HOME/NuGetPackages"


export _Z_DATA=$HOME/.local/share/z/z
export STARDICT_DATA_DIR=$HOME/.local/share/stardict/
export ABOOKRC=$HOME/.config/abook/abookrc
export ABOOKDATA=$HOME/.local/share/abook/addressbook
export VIT_DIR="$HOME/.config/vit/"
# zsh clean up
export HISTFILE="$XDG_STATE_HOME"/zsh/history



# so that there isn't a .npmrc file in the home directory
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

# for java programs in general to not clutter the home directory
# sources: https://wiki.archlinux.org/title/XDG_Base_Directory the sts4 section
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java -Dlanguageserver.boot.symbolCacheDir=$XDG_CACHE_HOME/sts4/symbolCache"
# for maven to not clutter the home directory
export MAVEN_OPTS="-Dmaven.repo.local="$XDG_DATA_HOME"/maven/repository"
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export VJA_CONFIGDIR="$HOME/.config/vja"
export LINKDING_CONFIG="$HOME/.config/linkding/config.json"
