[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"
plug "zap-zsh/supercharge"
plug "zsh-users/zsh-syntax-highlighting"
plug "kutsan/zsh-system-clipboard"
plug "jeffreytse/zsh-vi-mode"
plug "zsh-users/zsh-autosuggestions"
