[mgr]
sort_by = "mtime"
sort_reverse = true

[opener]
pdf = [
	{ run = 'sioyek "$@"', orphan = true, for = "unix" },
]

[plugin]
prepend_spotters = [
  { url = "*/", run = "spot" },
  { url = "*", run = "spot-tmsu" },
  { mime = "audio/*", run = "spot-audio" },
  { mime = "video/*", run = "spot-video" },
]
