src_module(){
  ZSH_MODULES="$HOME/.config/zsh/modules"
  module="$ZSH_MODULES/$1"
  [[ -f "$module" ]] && source "$module"
}

# ORDER MATTERS

# first load plugins
src_module "plugins.zsh"

# then some custom bindings
src_module "bindings.zsh"

# defined enviroment variables(not related to xdg compliance)
src_module "exports.zsh"

# defined aliases (not related to xdg compliance)
src_module "aliases.zsh"

src_module "functions.zsh"

# env vars and aliases related to xdg compliance
src_module "cleanup.vars.zsh"
src_module "cleanup.aliases.zsh"

# completion setups for zsh
src_module "completion.zsh"

# extra stuff
src_module "extra.zsh"
