#!/usr/bin/env bash
# This file was extracted from: https://github.com/Traap/dotfiles/blob/master/bash/bin/fr
# shout out to him as well, great script!
#
# Find a pattern with rg and fzf.  Preview contents with bat.  Edit File.
#
# Dependencies:
#   1. rg  | recursively search current directory for lines matching a pattern
#   2. fzf | command-line fuzzy finder
#   3. bat | a cat clone with syntax highlighting and Git integration
#   4. $EDITOR | Exported environment variable referring to your editor.
#
# Shout Out:
# https://github.com/junegunn/fzf/blob/master/ADVANCED.md#using-fzf-as-interactive-ripgrep-launcher
#
# 1. Search for text in files using Ripgrep
# 2. Interactively restart Ripgrep with reload action
# 3. Open the file in $EDITOR

# --preview 'pdftotext {1} - | bat --highlight-line {3}' \

RG_PREFIX="pdfgrep --with-filename --page-number  --color=always  --ignore-case --recursive"
INITIAL_QUERY="${*:-}"
IFS=: read -ra selected < <(
  FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY")" \
  fzf --ansi \
      --disabled --query "$INITIAL_QUERY" \
      --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
      --delimiter : \
      --preview 'pdftotext {1} - | bat --color=always $( pdftotext {1} - | grep -Fn {q} | cut -d: -f1 | xargs -I {} echo -H {} | tr "\n" " ")' \
      --preview-window "left,50%,border-bottom"
)
# --preview-window "left,50%,border-bottom,+{n}+3/3,~3"
[ -n "${selected[0]}" ] && setsid -f sioyek --new-window "${selected[0]}" --page "${selected[1]}" 2>/dev/null
