#!/bin/bash
# script to simplify a timer with music

title=""
sound=""
time=$1
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --tittle|-T)
            title=$2
            shift
            ;;
        --sound|-S)
            sound=$2
            shift
            ;;
    esac
    shift
done
notification_sound=""
for dir in "$HOME/.local/share" ${XDG_DATA_DIRS//:/ }; do
    if [[ -f "$dir/sounds/freedesktop/stereo/alarm-clock-elapsed.oga" ]]; then
        notification_sound="$dir/sounds/freedesktop/stereo/alarm-clock-elapsed.oga"
        break
    fi
done

termdown "$time" -T "$title" && {
    if [[ -n "$notification_sound" && -f "$notification_sound" ]]; then
        paplay "$notification_sound" 2>/dev/null || notify-send "Timer finished" "Could not play sound"
    else
        notify-send "Timer finished" "No sound file found"
    fi
}
