#!/bin/bash
repo_file="$HOME/.config/tmux/task_repo_name"
parent_dir="/home/marcos/Documents/Areas/Obsidian"
repo_name=$(cat "$repo_file")
repo="$parent_dir/$repo_name"
rg "^\s*- \[-\].*#_progress" "$repo" -A 1 -B 1 --color=always | sed "s|$parent_dir/||g" | less -R
