# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: "::date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ":now"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%dT%H:%M:%S"
  - trigger: "::ts"
    replace: "{{timestamp}}"
    vars:
      - name: timestamp
        type: shell
        params:
          cmd: "date +%s"
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  - trigger: "`e`"
    replace: "è"
  - trigger: "^e^"
    replace: "ê"

  - trigger: ":e:"
    replace: "ë"

  - trigger: "^o^"
    replace: "ô"

  - trigger: "`a`"
    replace: "à"

  - trigger: ",s,"
    replace: "ş"

  - trigger: ":o:"
    replace: "ö"
  - trigger: "^a^"
    replace: "â"

  - trigger: "^i^"
    replace: "î"

  - trigger: ":i:"
    replace: "ï"

  - trigger: "`u`"
    replace: "ù"

  - trigger: "^u^"
    replace: "û"

  - trigger: ":u:"
    replace: "ü"

  - trigger: ":oe:"
    replace: "œ"

  - trigger: ":ae:"
    replace: "æ"

  - trigger: ":y:"
    replace: "ÿ"

  - trigger: ",c,"
    replace: "ç"

  - trigger: "`E`"
    replace: "È"

  - trigger: "^E^"
    replace: "Ê"

  - trigger: ":E:"
    replace: "Ë"

  - trigger: "^O^"
    replace: "Ô"

  - trigger: "`A`"
    replace: "À"

  - trigger: "^A^"
    replace: "Â"

  - trigger: "^I^"
    replace: "Î"

  - trigger: ":I:"
    replace: "Ï"

  - trigger: "`U`"
    replace: "Ù"

  - trigger: "^U^"
    replace: "Û"

  - trigger: ":U:"
    replace: "Ü"

  - trigger: "::oe"
    replace: "œ"

  - trigger: ":OE"
    replace: "Œ"

  - trigger: ":AE"
    replace: "Æ"

  - trigger: ":Y:"
    replace: "Ÿ"

  - trigger: ",C,"
    replace: "Ç"

  - trigger: "'?'"
    replace: "¿"
  - trigger: "'!'"
    replace: "¡"
  - trigger: "'n'"
    replace: "ñ"
  - trigger: "'N'"
    replace: "Ñ"
  - trigger: "'a'"
    replace: "á"
  - trigger: "'e'"
    replace: "é"
  - trigger: "'i'"
    replace: "í"
  - trigger: "'o'"
    replace: "ó"
  - trigger: "'u'"
    replace: "ú"
  - trigger: "'A'"
    replace: "Á"
  - trigger: "'E'"
    replace: "É"
  - trigger: "'I'"
    replace: "Í"
  - trigger: "'O'"
    replace: "Ó"
  - trigger: "'U'"
    replace: "Ú"
